######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 11:34:15 2016
######################################################################

QT += testlib
QT += core gui
QT += positioning

TEMPLATE = app
TARGET = frontend_unit_test
INCLUDEPATH += .
INCLUDEPATH += ../src

CONFIG += testlib

MOC_DIR = $$PWD

QMAKE_POST_LINK += ./${TARGET}

CONFIG +=   c++11

# Input
SOURCES += detection_test.cpp \
        frontend_test.cpp

include(../src/core/core.pri)
