######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 11:34:15 2016
######################################################################

QT += testlib
QT += core gui

TEMPLATE = app
TARGET = frontend_unit_test
INCLUDEPATH += .
INCLUDEPATH += ../../frontend


# Input
SOURCES += frontend_test.cpp
include(../../frontend/core/core.pri)
